"""    
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8 , 13, 21, 34, 55, 89
"""
def fibonacci(i: int) -> int:
    """
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.
    """
    if i <= 2:
        return i
    else:
        return fibonacci(i - 1) + fibonacci(i - 2)

def fibonacci_list(i: int) -> list:
    """
    Return List of Fibonacci Sequence
    """
    output = []
    for _ in range(1, i+1):
        number = fibonacci(_)
        if number < 4000000 and number % 2 == 0:
            output.append(fibonacci(_))
        if number >= 4000000:
            print(f"The Fibonacci Value increase 4 Million at the {_} number")
            break
    return output

print(f"The Sum of Even Fibonacci Numbers that are even is {sum(fibonacci_list(200))}")
